### ISSUE TITLE
Manage groups page must be reopened after every restart

### ISSUE THREAD

**Issue by VeryLoudIcecream** [lambidu/tabs-group-extension#7]
In this extension's pop-up window, there is an option to launch the manage groups page, where users can handily view a list of all tabs in a group.

However, this page must be reopened every time. When it is reloaded -- either via a page refresh, or after starting Firefox -- my browser cannot find it again. 

The ability to have the manage groups page open automatically when the browser is launched would eliminate the frustration of loading it every time, and would streamline users workflow.

**Comment by lambidu** [comment]
Right now this isn't possible because of security implied by the browser, to help protect users from being tracked.
There are some work in progress to make that possible but it's in early stage of developing.
I'll keep eye on this and implement as soon as it will become available.

Discussion on the topic can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1322304), if you're interested.
